# Generated by Django 2.2 on 2019-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0002_auto_20190411_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=1),
        ),
    ]
