# Generated by Django 2.2 on 2019-04-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmweb', '0003_rate_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='MovieRate',
        ),
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='MovieComment',
        ),
        migrations.CreateModel(
            name='MovieSubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='filmweb.MovieComment')),
            ],
        ),
    ]
