# Generated by Django 2.2 on 2019-04-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0004_auto_20190413_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierate',
            name='rate',
            field=models.FloatField(),
        ),
    ]
