# Generated by Django 2.2 on 2019-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0006_auto_20190416_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.DeleteModel(
            name='MovieCategory',
        ),
    ]
