# Generated by Django 2.2 on 2019-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0007_auto_20190416_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='filmweb.MovieCategory'),
        ),
    ]
