# Generated by Django 2.2 on 2019-04-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0008_auto_20190416_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rates_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rates_count',
            field=models.IntegerField(default=0),
        ),
    ]
