# Generated by Django 2.2 on 2019-05-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0012_auto_20190507_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='title',
        ),
    ]
