# Generated by Django 2.2 on 2019-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0013_remove_moviereview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='title',
            field=models.TextField(default='xD'),
            preserve_default=False,
        ),
    ]
