# Generated by Django 2.2 on 2019-05-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0014_moviereview_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='title',
        ),
    ]
