# Generated by Django 2.2 on 2019-05-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0015_auto_20190507_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
