# Generated by Django 2.2 on 2019-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0016_auto_20190507_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='no_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='yes_votes',
            field=models.IntegerField(default=0),
        ),
    ]
