# Generated by Django 2.2 on 2019-05-07 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0017_auto_20190507_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='helped',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
